const K='ata_v1';let db=JSON.parse(localStorage.getItem(K)||'null')||{settings:{commission:40},batches:[],students:[],payments:[],expenses:[],teachers:[]};
const save=()=>localStorage.setItem(K,JSON.stringify(db)),M=n=>'Rs. '+Math.round(n||0).toLocaleString('en-PK'),$=id=>document.getElementById(id);
const id=p=>p+Date.now()+Math.random().toString(36).slice(2,5);
function login(){if($('u').value==='admin'&&$('pw').value==='admin123'){$('login').classList.add('hidden');$('app').classList.remove('hidden');go('dashboard')}else alert('Invalid login')}
const pages=['dashboard','batches','students','payments','dues','teachers','expenses','profit'];$('nav').innerHTML=pages.map(x=>`<a data-p="${x}" onclick="go('${x}')">${x==='profit'?'Profit & Loss':x.replace(/^./,x[0].toUpperCase())}</a>`).join('');
function go(p){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.p===p));$('title').textContent=p==='profit'?'Profit & Loss':p[0].toUpperCase()+p.slice(1);({dashboard,batches,students,payments,dues,teachers,expenses,profit}[p]||dashboard)()}
function paid(s){return db.payments.filter(p=>p.studentId===s.id).reduce((a,p)=>a+p.amount,0)}
function rem(s){return Math.max(0,s.fee-paid(s))}
function totals(){let r=db.payments.reduce((a,p)=>a+p.amount,0),c=db.payments.reduce((a,p)=>a+p.commission,0),e=db.expenses.reduce((a,p)=>a+p.amount,0),v=db.students.reduce((a,s)=>a+s.fee,0);return{r,c,e,v,o:v-r,n:r-c-e}}
function card(a,b,c=''){return `<div class="card"><small>${a}</small><h2 class="${c}">${b}</h2></div>`}
function dashboard(){let t=totals();$('content').innerHTML=`<div class="cards">${card('Active Students',db.students.filter(s=>s.status==='Active').length)}${card('Batches',db.batches.length)}${card('Fee Received',M(t.r),'green')}${card('Outstanding',M(t.o),'red')}${card('Teacher 40%',M(t.c))}${card('Other Expenses',M(t.e))}${card('Course Value',M(t.v))}${card('Net Profit/Loss',M(t.n),t.n>=0?'green':'red')}</div><div class="grid"><div class="panel"><h3>Recent Payments</h3>${payTable(db.payments.slice(-7).reverse())}</div><div class="panel"><h3>Outstanding Fees</h3>${dueTable(db.students.filter(s=>rem(s)>0))}</div></div>`}
function batches(){let rows=db.batches.map(b=>{let ss=db.students.filter(s=>s.batchId===b.id),ps=db.payments.filter(p=>ss.some(s=>s.id===p.studentId)),r=ps.reduce((a,p)=>a+p.amount,0),c=ps.reduce((a,p)=>a+p.commission,0),e=db.expenses.filter(x=>x.batchId===b.id).reduce((a,x)=>a+x.amount,0);return `<tr><td>${b.name}<br><small>${b.course}</small></td><td>${b.teacher}</td><td>${ss.length}</td><td>${M(ss.reduce((a,s)=>a+s.fee,0))}</td><td>${M(r)}</td><td>${M(r-c-e)}</td><td class="actions"><button onclick="studentForm('${b.id}')">+ Student</button></td></tr>`}).join('');$('content').innerHTML=`<div class="toolbar"><span></span><button onclick="batchForm()">+ Add Batch</button></div><div class="panel"><div class="tablewrap"><table class="table"><tr><th>Batch</th><th>Teacher</th><th>Students</th><th>Course Value</th><th>Received</th><th>Profit</th><th></th></tr>${rows||'<tr><td colspan=7 class=empty>No batches</td></tr>'}</table></div></div>`}
function students(){let rows=db.students.map(s=>`<tr><td>${s.name}<br><small>${s.phone||''}</small></td><td>${db.batches.find(b=>b.id===s.batchId)?.name||'-'}</td><td>${M(s.fee)}</td><td>${M(paid(s))}</td><td>${M(rem(s))}</td><td><span class="badge">${s.status}</span></td><td class="actions"><button onclick="feeForm('${s.id}')">Receive</button><button onclick="viewStudent('${s.id}')">View</button></td></tr>`).join('');$('content').innerHTML=`<div class="toolbar"><span></span><button onclick="studentForm()">+ Add Student</button></div><div class="panel"><div class="tablewrap"><table class="table"><tr><th>Student</th><th>Batch</th><th>Fee</th><th>Paid</th><th>Remaining</th><th>Status</th><th></th></tr>${rows||'<tr><td colspan=7 class=empty>No students</td></tr>'}</table></div></div>`}
function payments(){ $('content').innerHTML=`<div class="toolbar"><span></span><button onclick="feeForm()">+ Receive Fee</button></div><div class="panel">${payTable(db.payments.slice().reverse())}</div>`}
function payTable(arr){if(!arr.length)return'<div class="empty">No payments yet.</div>';return `<div class="tablewrap"><table class="table"><tr><th>Date</th><th>Student</th><th>Amount</th><th>Teacher 40%</th><th>Academy 60%</th><th>Method</th><th></th></tr>${arr.map(p=>`<tr><td>${p.date}</td><td>${db.students.find(s=>s.id===p.studentId)?.name||'-'}</td><td>${M(p.amount)}</td><td>${M(p.commission)}</td><td>${M(p.academy)}</td><td>${p.method}</td><td><button onclick="receipt('${p.id}')">Receipt</button></td></tr>`).join('')}</table></div>`}
function dues(){$('content').innerHTML=`<div class="panel"><h3>Pending Fees</h3>${dueTable(db.students.filter(s=>rem(s)>0))}</div>`}
function dueTable(arr){if(!arr.length)return'<div class="empty">No outstanding fees 🎉</div>';return `<div class="tablewrap"><table class="table"><tr><th>Student</th><th>Batch</th><th>Remaining</th><th>Due Date</th><th></th></tr>${arr.map(s=>`<tr><td>${s.name}</td><td>${db.batches.find(b=>b.id===s.batchId)?.name||'-'}</td><td>${M(rem(s))}</td><td>${s.due||'-'}</td><td><button onclick="feeForm('${s.id}')">Receive</button></td></tr>`).join('')}</table></div>`}
function teachers(){$('content').innerHTML=`<div class="toolbar"><span></span><button onclick="teacherForm()">+ Add Teacher</button></div><div class="panel"><table class="table"><tr><th>Teacher</th><th>Students</th><th>Received</th><th>Commission</th><th>Academy</th></tr>${db.teachers.map(t=>{let ss=db.students.filter(s=>s.teacherId===t.id),ps=db.payments.filter(p=>ss.some(s=>s.id===p.studentId)),r=ps.reduce((a,p)=>a+p.amount,0),c=ps.reduce((a,p)=>a+p.commission,0);return`<tr><td>${t.name}</td><td>${ss.length}</td><td>${M(r)}</td><td>${M(c)}</td><td>${M(r-c)}</td></tr>`}).join('')}</table></div>`}
function expenses(){$('content').innerHTML=`<div class="toolbar"><span></span><button onclick="expenseForm()">+ Add Expense</button></div><div class="panel"><table class="table"><tr><th>Date</th><th>Name</th><th>Category</th><th>Amount</th></tr>${db.expenses.slice().reverse().map(e=>`<tr><td>${e.date}</td><td>${e.name}</td><td>${e.cat}</td><td>${M(e.amount)}</td></tr>`).join('')}</table></div>`}
function profit(){let t=totals();$('content').innerHTML=`<div class="cards">${card('Fee Received',M(t.r),'green')}${card('Teacher Commission',M(t.c))}${card('Expenses',M(t.e))}${card('NET '+(t.n>=0?'PROFIT':'LOSS'),M(t.n),t.n>=0?'green':'red')}</div><div class="panel" style="margin-top:18px"><h3>Academy Calculation</h3><p>Actual fee received: <b>${M(t.r)}</b></p><p>Teacher commission (40% of actual payments): <b>${M(t.c)}</b></p><p>Other expenses: <b>${M(t.e)}</b></p><hr><h2 class="${t.n>=0?'green':'red'}">${t.n>=0?'NET PROFIT':'NET LOSS'}: ${M(t.n)}</h2><p>Outstanding fee (not counted as received): <b>${M(t.o)}</b></p></div>`}
function modal(t,b){$('mt').textContent=t;$('mb').innerHTML=b;$('modal').classList.remove('hidden')}function closeM(){$('modal').classList.add('hidden')}
function batchForm(){modal('Add Batch',`<div class=formgrid><label>Batch Name<input id=bn></label><label>Course<input id=bc></label><label>Teacher<input id=bt></label><label>Duration<input id=bd placeholder="4 Months"></label><label>Timing<input id=bi></label><label>Start Date<input id=bs type=date></label></div><button onclick="addBatch()">Save</button>`)}
function addBatch(){let b={id:id('b'),name:$('bn').value,course:$('bc').value,teacher:$('bt').value,duration:$('bd').value,timing:$('bi').value,start:$('bs').value};if(!b.name||!b.course)return alert('Enter batch and course');db.batches.push(b);if(b.teacher&&!db.teachers.some(t=>t.name===b.teacher))db.teachers.push({id:id('t'),name:b.teacher});save();closeM();go('batches')}
function studentForm(bid=''){modal('Add Student',`<div class=formgrid><label>Name<input id=sn></label><label>Father Name<input id=sf></label><label>Phone<input id=sp></label><label>Admission Date<input id=sa type=date value="${new Date().toISOString().slice(0,10)}"></label><label>Batch<select id=sb>${db.batches.map(b=>`<option value="${b.id}" ${b.id===bid?'selected':''}>${b.name}</option>`).join('')}</select></label><label>Total Course Fee<input id=sfee type=number></label><label>Plan<select id=splan><option>Full Payment</option><option>2 Installments</option><option>3 Installments</option></select></label><label>Next Due<input id=sdue type=date></label></div><button onclick="addStudent()">Save Student</button>`)}
function addStudent(){let b=db.batches.find(x=>x.id===$('sb').value),t=db.teachers.find(x=>x.name===b?.teacher),s={id:id('s'),name:$('sn').value,father:$('sf').value,phone:$('sp').value,admission:$('sa').value,batchId:b.id,teacherId:t?.id,fee:Number($('sfee').value),plan:$('splan').value,due:$('sdue').value,status:'Active'};if(!s.name||!b||s.fee<=0)return alert('Complete required fields');db.students.push(s);save();closeM();go('students')}
function feeForm(sid){if(!sid&&db.students.length)sid=db.students[0].id;if(!sid)return alert('Add a student first');modal('Receive Fee',`<label>Student<select id=ps>${db.students.map(s=>`<option value="${s.id}" ${s.id===sid?'selected':''}>${s.name} — ${M(rem(s))} remaining</option>`).join('')}</select></label><label>Amount<input id=pa type=number></label><label>Date<input id=pd type=date value="${new Date().toISOString().slice(0,10)}"></label><label>Method<select id=pm><option>Cash</option><option>Bank Transfer</option><option>Easypaisa</option><option>JazzCash</option><option>Other</option></select></label><label>Next Due Date<input id=pdu type=date></label><button onclick="addPay()">Save & Print Receipt</button>`)}
function addPay(){let s=db.students.find(x=>x.id===$('ps').value),a=Number($('pa').value);if(!s||a<=0||a>rem(s))return alert('Invalid amount');let rate=Number(db.settings.commission||40)/100,p={id:id('p'),studentId:s.id,amount:a,date:$('pd').value,method:$('pm').value,due:$('pdu').value,commission:a*rate,academy:a*(1-rate)};db.payments.push(p);if(p.due)s.due=p.due;if(rem(s)===0)s.status='Completed';save();closeM();receipt(p.id);go('payments')}
function teacherForm(){modal('Add Teacher',`<label>Name<input id=tn></label><label>Phone<input id=tp></label><button onclick="db.teachers.push({id:id('t'),name:$('tn').value,phone:$('tp').value});save();closeM();go('teachers')">Save</button>`)}
function expenseForm(){modal('Add Expense',`<label>Name<input id=en></label><label>Amount<input id=ea type=number></label><label>Date<input id=ed type=date value="${new Date().toISOString().slice(0,10)}"></label><label>Category<select id=ec><option>Electricity</option><option>Internet</option><option>Rent</option><option>Marketing</option><option>Equipment</option><option>Stationery</option><option>Maintenance</option><option>Other</option></select></label><button onclick="addExp()">Save</button>`)}
function addExp(){let e={id:id('e'),name:$('en').value,amount:Number($('ea').value),date:$('ed').value,cat:$('ec').value};if(!e.name||e.amount<=0)return alert('Invalid expense');db.expenses.push(e);save();closeM();go('expenses')}
function viewStudent(idv){let s=db.students.find(x=>x.id===idv),ps=db.payments.filter(p=>p.studentId===idv);modal('Student Profile',`<h3>${s.name}</h3><p>Batch: ${db.batches.find(b=>b.id===s.batchId)?.name||'-'}</p><p>Total: <b>${M(s.fee)}</b> | Paid: <b>${M(paid(s))}</b> | Remaining: <b>${M(rem(s))}</b></p>${payTable(ps)}`)}
function receipt(pid){let p=db.payments.find(x=>x.id===pid),s=db.students.find(x=>x.id===p.studentId),b=db.batches.find(x=>x.id===s.batchId),prev=paid(s)-p.amount,w=open('','_blank');w.document.write(`<html><head><title>Fee Receipt</title><style>body{font-family:Arial;max-width:800px;margin:30px auto;padding:20px;color:#172033}.head{text-align:center;border-bottom:2px solid #0755a7;padding-bottom:15px}.r{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding:9px}.ok{color:green;font-weight:bold}button{padding:10px;background:#0755a7;color:#fff;border:0}@media print{button{display:none}}</style></head><body><div class=head><h1>AL TAHIR TECH ACADEMY</h1><p>Learn To Serve Humanity</p><h2>FEE RECEIPT</h2></div><p><b>Receipt:</b> ${p.id}<br><b>Date:</b> ${p.date}</p><p><b>Student:</b> ${s.name}<br><b>Father:</b> ${s.father||'-'}<br><b>Course:</b> ${b?.course||'-'}<br><b>Batch:</b> ${b?.name||'-'}<br><b>Teacher:</b> ${b?.teacher||'-'}</p><div class=r><span>Total Course Fee</span><b>${M(s.fee)}</b></div><div class=r><span>Previous Paid</span><b>${M(prev)}</b></div><div class=r><span>Current Payment</span><b>${M(p.amount)}</b></div><div class=r><span>Total Paid</span><b>${M(paid(s))}</b></div><div class=r><span>Remaining</span><b>${M(rem(s))}</b></div><div class=r><span>Payment Method</span><b>${p.method}</b></div><div class=r><span>Teacher Commission (40%)</span><b>${M(p.commission)}</b></div><div class=r><span>Academy Share (60%)</span><b>${M(p.academy)}</b></div><p class="${rem(s)===0?'ok':''}">${rem(s)===0?'✓ PAID IN FULL':'Next Due: '+(p.due||'Not set')}</p><p>Authorized Signature: __________________</p><button onclick="print()">Print / Save as PDF</button></body></html>`);w.document.close()}
